name: Build and publish

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                    - os: windows-latest
                    - os: macos-latest

        steps:
            - uses: actions/checkout@v2

            - run: mkdir src

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: gcc -fPIC

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              run: gcc -fPIC

            - name: Build for macOS
              if: matrix.os == 'macos-latest'
              run: gcc -fno-common 

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: ${{ github.ref }}
